version: 2

models:

  - name: stg_customers
    description: This model cleans up customer data
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - not_null
          - unique 

  - name: stg_orders   
    description: This model cleans up order data
    columns:
      - name: order_id
        description: Primary key
        tests:
          - not_null
          - unique
      - name: status
        description: "{{ doc('order_status') }}"
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - relationships:
              field: customer_id
              to: ref('stg_customers')

sources:
  - name: jaffle_shop
    database: dbt-tutorial
    description: Schema with shop data
    schema: jaffle_shop
    tables:
      - name: orders
        description: Orders raw data
        loaded_at_field: loaded_at
        freshness: 
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        

      - name: customers
        description: Customers raw data